---
protocol-key-pair:
  path: /opt/sui/keys/protocol.key
worker-key-pair:
  path: /opt/sui/keys/worker.key
network-key-pair:
  path: /opt/sui/keys/network.key
db-path: /opt/sui/db/authorities_db
network-address: /ip4/0.0.0.0/tcp/8080/http
metrics-address: 0.0.0.0:9184
admin-interface-port: 1337
consensus-config:
  address: /ip4/127.0.0.1/tcp/8083/http
  db-path: /opt/sui/db/consensus_db
  internal-worker-address: null
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 2000ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/127.0.0.1/tcp/33291/http
    network_admin_server:
      primary_network_admin_server_port: 41303
      worker_network_admin_server_base_port: 41669
    block_synchronizer:
      range_synchronize_timeout: 30000ms
      certificates_synchronize_timeout: 30000ms
      payload_synchronize_timeout: 30000ms
      payload_availability_timeout: 30000ms
      handler_certificate_deliver_timeout: 30000ms
    consensus_api_grpc:
      socket_addr: /ip4/127.0.0.1/tcp/44579/http
      get_collections_timeout: 5000ms
      remove_collections_timeout: 5000ms
enable-event-processing: false
p2p-config:
  listen-address: 0.0.0.0:8084
  external-address: /dns/<VALIDATOR_HOSTNAME>/udp/8084
  anemo-config:
    max-concurrent-connections: 0
  seed-peers:
    - address: /dns/ewr-tnt-ssfn-00.testnet.sui.io/udp/8084
      peer-id: df8a8d128051c249e224f95fcc463f518a0ebed8986bbdcc11ed751181fecd38
    - address: /dns/lax-tnt-ssfn-00.testnet.sui.io/udp/8084
      peer-id: f9a72a0a6c17eed09c27898eab389add704777c03e135846da2428f516a0c11d
    - address: /dns/lhr-tnt-ssfn-00.testnet.sui.io/udp/8084
      peer-id: 9393d6056bb9c9d8475a3cf3525c747257f17c6a698a7062cbbd1875bc6ef71e
genesis:
  genesis-file-location: /opt/sui/config/genesis.blob
authority-store-pruning-config:
  num-latest-epoch-dbs-to-retain: 3
  epoch-db-pruning-period-secs: 3600
  num-epochs-to-retain: 1
  max-checkpoints-in-batch: 5
  max-transactions-in-batch: 1000
  smoothing: true
end-of-epoch-broadcast-channel-capacity: 128
checkpoint-executor-config:
  checkpoint-execution-max-concurrency: 200
  local-execution-timeout-sec: 10
db-checkpoint-config:
  perform-db-checkpoints-at-epoch-end: false
indirect-objects-threshold: 18446744073709551615
metrics:
  push-interval-seconds: 60
  push-url: https://metrics-proxy.testnet.sui.io:8443/publish/metrics